-- Revising the Select Query I
SELECT *
FROM CITY
WHERE COUNTRYCODE='USA' AND POPULATION >=100000;

-- Revising the Select Query II
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION >= 120000;

-- Select All
SELECT *
FROM CITY

-- Select-by-id
SELECT *
FROM CITY
WHERE ID=1661;


-- Japanese-cities-attributes
SELECT *
FROM CITY
WHERE COUNTRYCODE='JPN'

-- Name-of-employees
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME ASC

-- Salary-of-employees
SELECT NAME
FROM EMPLOYEE
WHERE MONTHS < 10 AND SALARY > 2000  
ORDER BY EMPLOYEE_ID ASC
